services:
  - type: web
    name: reelixx-backend
    env: python
    plan: free
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12

  - type: web
    name: reelixx-frontend
    env: node
    plan: free
    rootDir: frontend
    buildCommand: npm ci && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: NEXT_PUBLIC_API_BASE
        # This will auto-point frontend to the backend URL Render gives you
        fromService:
          type: web
          name: reelixx-backend
          property: host
