# docker-compose.yml for local development
version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: reelixx
      POSTGRES_USER: reelixx
      POSTGRES_PASSWORD: reelixx
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://reelixx:reelixx@db:5432/reelixx
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - REELIXX_FREE_MODE=${REELIXX_FREE_MODE:-1}
    depends_on:
      - db
    volumes:
      - ./app/exports:/app/app/exports
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  postgres_data:
